### ISSUE TITLE
Missing dependency package `yourdfpy`

### ISSUE THREAD

**Issue by Danfoa** [robot-descriptions/robot_descriptions.py#12]
Good Day, 

This issue is just to call attention to a missing dependency during package build and install. Specifically, `yourdfpy` package is missing as a description and throws an error when using the CLI.

I will submit a pull request with the change soon if it is not easily fixed. 

PS: THANKS for this package, you save hours of pain in the ass to any newcomer in robotics.

**Comment by stephane-caron** [comment]
Thanks for your feedback :slightly_smiling_face: If everything is implemented correctly `yourdfpy` should be an optional dependency (e.g. ``pip install robot_descriptions[cli]`` installs it):

1. There shouldn't be any yourdfpy-related import error when doing ``import robot_descriptions``
2. If an example or sub-module uses it, it should raise a user-friendly instruction such as "Importing this module requires yourdfpy, you can install it by..."

I see that point 2 was lacking, so I started a PR for it: https://github.com/robot-descriptions/robot_descriptions.py/pull/13 @Danfoa feel free to review and let me know if that would fix it for you.
