### ISSUE TITLE
Wheeled robots

### ISSUE THREAD

**Issue by manavkulshrestha** [robot-descriptions/robot_descriptions.py#41]
The README specifies there's wheeled robots but the hyperlink does not show any. Why is this?

**Comment by stephane-caron** [comment]
Thank you for pointing this out :smiley: This error happened when importing the list of [awesome robot descriptions](https://github.com/robot-descriptions/awesome-robot-descriptions). That list has wheeled robots, but all of them are distributed in the Xacro format that Python libraries don't parse directly.
