### ISSUE TITLE
Bumping version of example-robot-data repository

### ISSUE THREAD

**Issue by htadashi** [robot-descriptions/robot_descriptions.py#54]
First of all, thank you so much for maintaining this valuable repository! 

It would be possible to bump the version of example-robot-data in https://github.com/robot-descriptions/robot_descriptions.py/blob/ae81aed222d7064453d12a3a164a42bc98dd0d7d/robot_descriptions/_repositories.py#L89-L93
to release 4.0.9 (commit `d0d9098d752014aec3725b07766962acf06c5418`)? 

Unfortunately, the version v4.0.3 does not include the inertial parameters in the Franka panda robot, limiting the usage of the URDF file for some applications.

**Comment by stephane-caron** [comment]
Sure thing, feel free to open a PR with this change. We can merge straight away when the CI passes.

**Comment by htadashi** [comment]
Thank you very much! I opened a PR in #55.
