### ISSUE TITLE
Some descriptions don't load properly in Pinocchio

### ISSUE THREAD

**Issue by stephane-caron** [robot-descriptions/robot_descriptions.py#6]
Some URDF descriptions don't load properly in Pinocchio. At present, the descriptions that don't load properly are:

| Description | Pinocchio 2.6.4 | Pinocchio 2.6.10 |
|--|--|--|
| `cf2_description` | ❌ | :heavy_check_mark: |
| `laikago_description` | ❌ | :heavy_check_mark: |
| `mini_cheetah_description` | ❌ | ❌ |
| `minitaur_description` | ❌ | ❌ |
| `pr2_description` | ❌ | ❌ |

Some of them were because of https://github.com/stack-of-tasks/pinocchio/issues/1741. A fix was proposed by Pinocchio maintainers in https://github.com/stack-of-tasks/pinocchio/pull/1742 which made it to 2.6.10.

This issue is here to keep track, and check that Pinocchio eventually loads all of these descriptions successfully.

**Comment by jcarpent** [comment]
Do you need a new release?

**Comment by stephane-caron** [comment]
That would be great! Then I could check this issue within https://github.com/stephane-caron/robot_descriptions.py/pull/5 (which checks that all URDFs are loading properly in Pinocchio)

The CI pulls its dependencies from pip, as it is assumed that's where most users are getting their dependencies from as well.

**Comment by jcarpent** [comment]
cc @nim65s

**Comment by stephane-caron** [comment]
> Could you use conda for the CI?

Well, the CI runs pip because the package ships for pip users. I'm 100% open to adding conda to the CI as well, so that the package ships for conda users too. But that would be in addition to pip, so that we don't leave pip users behind.

**Comment by stephane-caron** [comment]
Sounds good! Let's keep track of it at https://github.com/stack-of-tasks/pinocchio/issues/1745

I'll keep this issue open here until all URDF descriptions load successfully with Pinocchio from PyPI.

**Comment by nim65s** [comment]
Hi @stephane-caron,
I've build pin-2.6.10-0-cp310-cp310-manylinux_2_24_x86_64.whl and its dependencies and uploaded in on PyPI test instance.

It is for CPython 3.10 on linux x86_64. Could you test it ?
```
python -m pip install -U pip
python -m pip install tomli numpy
python -m pip install --index-url https://test.pypi.org/simple/ pin
```

**Comment by stephane-caron** [comment]
Great! I can tell https://github.com/stack-of-tasks/pinocchio/pull/1742 had an effect, because some of the problematic descriptions now load, but not all of them:

| Description | Pinocchio 2.6.4 | Pinocchio 2.6.10 |
|--|--|--|
| `cf2_description` | ❌ | :heavy_check_mark: |
| `laikago_description` | ❌ | :heavy_check_mark: |
| `mini_cheetah_description` | ❌ | ❌ |
| `minitaur_description` | ❌ | ❌ |
| `pr2_description` | ❌ | ❌ |

Details:

* `mini_cheetah_description`: ValueError: Mesh meshes/mini_body.obj could not be found.
* `minitaur_description`: ValueError: Mesh tmotor3.obj could not be found.
* `pr2_description`: ValueError: Mesh meshes/base_v0/base_L.stl could not be found.

**Comment by Danfoa** [comment]
Both Solo and Bolt do now load with Pin 2.6.4 either

**Comment by stephane-caron** [comment]
Checking back on this issue, I see that the three remaining descriptions don't load yet, as of Pinocchio 2.6.10. Moving it to a separate issue:

- In robot_descriptions.py to keep track: https://github.com/robot-descriptions/robot_descriptions.py/issues/15
- In Pinocchio: https://github.com/stack-of-tasks/pinocchio/issues/1786

All issues mentioned in this thread are either solved or have a more specific follow-up.
